CREATE TABLE IF NOT EXISTS vip_meta (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    vip_id BIGINT UNSIGNED DEFAULT NULL,
    request_method VARCHAR(10) NOT NULL,
    request_path VARCHAR(255) NOT NULL,
    query_string TEXT DEFAULT NULL,
    ip_address VARCHAR(45) DEFAULT NULL,
    forwarded_for VARCHAR(255) DEFAULT NULL,
    user_agent TEXT DEFAULT NULL,
    referer_url TEXT DEFAULT NULL,
    origin_url VARCHAR(255) DEFAULT NULL,
    host_name VARCHAR(255) DEFAULT NULL,
    accept_language VARCHAR(255) DEFAULT NULL,
    browser_name VARCHAR(100) DEFAULT NULL,
    browser_version VARCHAR(50) DEFAULT NULL,
    os_name VARCHAR(100) DEFAULT NULL,
    os_version VARCHAR(50) DEFAULT NULL,
    device_type VARCHAR(50) DEFAULT NULL,
    ip_lookup_location VARCHAR(255) DEFAULT NULL,
    extra_payload JSON DEFAULT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
